In [98]:
import pandas as pd
import numpy as np


In [99]:
data = pd.read_csv("Train/Train.csv")

data.head()

X_train = data.get("review")
Y_train = data.get("label")

X_train.head()

X_train[1].split(". ")

data = pd.read_csv("Test/Test.csv")

X_test = data.get("review")

In [100]:
document="""My name is tarang. My age is 21. I like to code."""

In [101]:
s=[]

In [102]:
def splitter(i):
    i=i.replace("<br /><br />"," ")
    s=i.split(". ")
    return s

In [103]:
s=splitter(document)

In [104]:
print(s)

['My name is tarang', 'My age is 21', 'I like to code.']


In [105]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [106]:
sent_tokenize?

Signature: sent_tokenize(text, language='english')
Docstring:
Return a sentence-tokenized copy of *text*,
using NLTK's recommended sentence tokenizer
(currently :class:`.PunktSentenceTokenizer`
for the specified language).

:param text: text to split into sentences
:param language: the model name in the Punkt corpus
File:      c:\users\taran\appdata\local\programs\python\python39\lib\site-packages\nltk\tokenize\__init__.py
Type:      function


In [107]:
sents=sent_tokenize(document)

In [108]:
sents


['My name is tarang.', 'My age is 21.', 'I like to code.']

In [109]:
len(sents)

3

In [110]:
words=word_tokenize(sents[0],"english")

In [111]:
words

['My', 'name', 'is', 'tarang', '.']

In [112]:
from nltk.tokenize import regexp_tokenize

In [113]:
regexp_tokenize?

Signature:
regexp_tokenize(
    text,
    pattern,
    gaps=False,
    discard_empty=True,
    flags=re.UNICODE|re.MULTILINE|re.DOTALL,
)
Docstring:
Return a tokenized copy of *text*.  See :class:`.RegexpTokenizer`
for descriptions of the arguments.
File:      c:\users\taran\appdata\local\programs\python\python39\lib\site-packages\nltk\tokenize\regexp.py
Type:      function


## Main Code

In [114]:
words=regexp_tokenize(sents[0],'[a-zA-z]+')

In [115]:
words

['My', 'name', 'is', 'tarang']

In [116]:
from nltk.corpus import stopwords

In [117]:
main_words = stopwords.words("english")

In [118]:
needed_words=[i for i in words if i not in main_words]

In [119]:
needed_words

['My', 'name', 'tarang']

In [120]:
from nltk.stem.snowball import SnowballStemmer

In [121]:
ss=SnowballStemmer("english")

In [122]:
steemed_words=[]

In [123]:
for needed_word in needed_words:
    if ss.stem(needed_word) not in steemed_words:
        steemed_words.append(ss.stem(needed_word))
    

In [124]:
steemed_words

['my', 'name', 'tarang']

In [125]:
def temp_token(document):
    
    document=document.replace("<br /><br />"," ")
    words=regexp_tokenize(document,'[a-zA-z]+')
    
    needed_words=[i for i in words if i not in main_words]
    
    steemed_words=[]
    for needed_word in needed_words:
        if ss.stem(needed_word) not in steemed_words:
            steemed_words.append(ss.stem(needed_word))
    
    return steemed_words

In [126]:
temp_token(X_train[0])

['matur',
 'intellig',
 'high',
 'charg',
 'melodrama',
 'unbelivebl',
 'film',
 'china',
 'wei',
 'stun',
 'perform',
 'catylast',
 'love',
 'triangl',
 'simpli',
 'oppurun',
 'see',
 'magnific',
 'take']

In [127]:
from sklearn.feature_extraction.text import CountVectorizer

In [128]:
cv=CountVectorizer(tokenizer=temp_token)
vectorised_documents=cv.fit_transform(sents)

In [129]:
vectorised_documents.shape

(3, 5)

In [88]:
vectorised_documents.toarray()

array([[0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0]], dtype=int64)

In [89]:
cv.vocabulary_

{'name': 3, 'tarang': 4, 'age': 0, 'like': 2, 'code': 1}

In [90]:
final=[]

In [91]:
for i in X_train[:2000]:
    tt_value=temp_token(i)
    sents=" ".join(tt_value)
    final.append(sents)

In [92]:
final[:2]

['matur intellig high charg melodrama unbelivebl film china wei stun perform catylast love triangl simpli oppurun see magnific take',
 'http video googl com videoplay docid hl en distribut tri we opt mass appeal want best possibl view rang forgo profit continu manual labor job glad entertain work texa tale pleas write if like alex stuie just your opinion rule']

In [93]:
cv=CountVectorizer(ngram_range=(1, 2))
vectorised_documents=cv.fit_transform(final)
vectorised_documents

<2000x182553 sparse matrix of type '<class 'numpy.int64'>'
	with 394944 stored elements in Compressed Sparse Row format>

In [96]:
print(vectorised_documents)

  (0, 98374)	1
  (0, 80679)	1
  (0, 73433)	1
  (0, 25977)	1
  (0, 99612)	1
  (0, 167947)	1
  (0, 57258)	1
  (0, 26955)	1
  (0, 175306)	1
  (0, 152753)	1
  (0, 117223)	1
  (0, 24425)	1
  (0, 94065)	1
  (0, 165757)	1
  (0, 143610)	1
  (0, 113061)	1
  (0, 138121)	1
  (0, 95557)	1
  (0, 155698)	1
  (0, 98385)	1
  (0, 80697)	1
  (0, 73448)	1
  (0, 25992)	1
  (0, 99624)	1
  (0, 167948)	1
  (0, 57355)	1
  (0, 26967)	1
  (0, 175307)	1
  (0, 152773)	1
  (0, 117267)	1
  (0, 24426)	1
  (0, 94354)	1
  (0, 165766)	1
  (0, 143695)	1
  (0, 113062)	1
  (0, 138406)	1
  (0, 95579)	1


In [54]:
final=[]
for i in X_test:
    tt_value=temp_token(i)
    sents=" ".join(tt_value)
    final.append(sents)
vectorised_documents_test=cv.transform(final)

In [55]:
print(vectorised_documents)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB

In [ ]:
mnb= MultinomialNB()

In [ ]:
mnb.fit(vectorised_documents,Y_train[:20000])

In [ ]:
y_=mnb.predict(vectorised_documents_test)

In [217]:
y_=pd.DataFrame(y_,columns=["label"])

In [220]:
y_.to_csv("OneDrive/Desktop/ML COdes/movie Rating Prediction by text review/submit_1.csv",index_label="Id")

In [ ]:
y_